version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: dbname
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  app:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000" # Expose FastAPI on port 8000
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://your_db_user:your_db_password@db/your_db_name
    env_file: .env
    #Optionally, set this in .env and use env_file


volumes:
  postgres_data: {} # This defines the postgres_data volume used by the db service