version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: dbname
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432" # Expose the PostgreSQL port for local connections

  app:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000" # Expose FastAPI on port 8000
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://your_db_user:your_db_password@db/your_db_name
      BRAVE_API_KEY: your_brave_api_key_here # Optionally, set this in .env and use env_file

volumes:
  postgres_data: # Named volume for persisting db data
